openapi: 3.2.0
info:
  version: 2.10.0
  description: 'Nerve OVDM API to manage:

    - node configuration

    - system configuration

    - system network configuration

    - workloads

    - remote connections

    - dna'
  title: Nerve Node DATAPATH API
  contact:
    name: Nerve support
    email: support@tttech-industrial.com
security:
- cookieAuth: []
tags:
- name: DATAPATH
paths:
  /api/auth/authenticate:
    get:
      summary: Authenticate Data Path user
      tags:
      - DATAPATH
      x-permissions:
      - DATAPATH:AUTHENTICATE_USER
      description: Authenticate a Data Path user for access.
      operationId: authenticate_data_path_user
      responses:
        '200':
          description: User authenticated successfully.
          content:
            text/plain; charset=utf-8:
              schema:
                description: Representing successfully response
                type: string
                example: OK
        '401':
          description: You are not authorized to perform this operation
          content:
            application/json:
              schema:
                oneOf:
                - type: object
                  description: User not authorized
                  required:
                  - user
                  additionalProperties: false
                  properties:
                    user:
                      type: string
                      description: Not authorized
                      enum:
                      - not authorized
                - type: object
                  description: User not authorized
                  required:
                  - status
                  - msg
                  additionalProperties: false
                  properties:
                    status:
                      type: integer
                      minimum: 401
                      maximum: 401
                      description: HTTP status code
                    msg:
                      type: string
                      description: Error message
                      enum:
                      - Not authorized
                      - not authorized
                - type: object
                  description: Cookie header is missing in the request
                  required:
                  - status
                  - message
                  - errors
                  additionalProperties: false
                  properties:
                    status:
                      description: HTTP status code
                      type: integer
                      enum:
                      - 401
                    message:
                      type: string
                      description: The validation error message
                      enum:
                      - '''cookie'' header required'
                    errors:
                      type: array
                      minItems: 1
                      maxItems: 1001
                      description: List of errors
                      items:
                        type: object
                        properties:
                          path:
                            type: string
                            minLength: 1
                            maxLength: 1001
                            description: Specified location within the document where the error occurred
                          message:
                            type: string
                            minLength: 1
                            maxLength: 1001
                            description: Error message
              examples:
                not_authorized_usr:
                  value:
                    user: not authorized
                not_authorized_status:
                  value:
                    status: 401
                    msg: Not authorized
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                description: Description of error associated with status code.
                required:
                - status
                - msg
                additionalProperties: false
                properties:
                  status:
                    type: integer
                    description: HTTP status code
                  msg:
                    type: string
                    minLength: 1
                    maxLength: 1001
                    description: Error message
                    pattern: .*
              examples:
                forbidden:
                  value:
                    status: 403
                    msg: Forbidden
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: header
      name: cookie
    basicAuth:
      type: http
      scheme: basic
